[package]
name = "librdiff-capi"
version = "0.0.0"
authors = ["Martin Pool <mbp@sourcefrog.net>"]
build = "build.rs"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
libc = "0.2"
librdiff = { version = "0", path = ".." }
