[package]
name = "rdiff-capi"
version = "0.0.0"
authors = ["Martin Pool <mbp@sourcefrog.net>"]
build = "build.rs"
license = "MIT"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
libc = "0.2"
rdiff = { version = "0", path = ".." }
