[package]
name = "rdiff-capi"
version = "0.0.0"
authors = ["Martin Pool <mbp@sourcefrog.net>"]
license = "MIT"

[lib]
name = "rdiff_capi"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
libc = "0.2"
rdiff = { version = "0", path = ".." }
