[package]
name = "librdiff-capi"
version = "3.0.0"
authors = ["Martin Pool <mbp@sourcefrog.net>"]

[lib]
# See https://github.com/rust-lang/rust/issues/19680
# XXX: Is this still needed with separated crates?
crate-type = ["dylib"]

[dependencies]
librdiff = {path = ".."}
